import React from "react";
import type {Metadata} from "next";
import {Roboto} from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
    title: "Veles | ",
    description: "Generated by create next app",
};

const roboto = Roboto({
    subsets: ['latin'],
    weights: ['400', '700'],
})

const FrontendRootLayout = ({
                                               children,
                                           }: Readonly<{
    children: React.ReactNode;
}>) => {
    const locale = "en"
    return (
        <html lang={locale}>
            <body className={roboto.className}>
                {children}
            </body>
        </html>
    );
}

export default FrontendRootLayout;
