import React from "react";
import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import '@/web/styles/admin/index.scss';

export const metadata: Metadata = {
    title: "Veles | Admin",
    description: "Generated by create next app",
};

const roboto = Roboto(
    {
        weight: ['300', '400', '500', '700'],
        subsets: ['latin'],
        display: 'swap',
        style: ['normal', 'italic'],
    }
)

const AdminRootLayout = ({children}: Readonly<{ children: React.ReactNode; }>) => {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}

export default AdminRootLayout;
