import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./(frontend)/globals.css";

export const metadata: Metadata = {
    title: "Veles | ",
    description: "Generated by create next app",
};

const roboto = Roboto(
    {
        weight: ['300', '400', '500', '700'],
        subsets: ['latin'],
        display: 'swap',
        style: ['normal', 'italic'],
    }
)

const RootLayout = ({
                                               children,
                                           }: Readonly<{
    children: React.ReactNode;
}>) => {
    const locale = "en"
    return (
        <html lang={locale}>
            <body className={roboto.className}>
                {children}
            </body>
        </html>
    );
}

export default RootLayout;
